spring.application.name=travelwebsite

server.port=${PORT:8080}
# Database config
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zwokruvvahhasxobnfws
spring.datasource.password=Travelwebsite2026

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary config
cloudinary.cloud_name=ds7h9l4xo
cloudinary.api_key=361849782764329
cloudinary.api_secret=t3PZxT7lS_kpSfiT38xrqsgAKcs

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=travelWebsiteSecretKeyForJwtAuthenticationMustBeLongEnough123456
app.jwt.expiration-ms=3600000
